language: generic
services:
  - docker
cache:
  directories:
  - docker_images
before_install:
- docker load -i docker_images/images.tar || true
before_cache:
- docker save -o docker_images/images.tar $(docker images -a -q)
script:
  - docker build -t shepherdjerred/overviewer:latest .
deploy:
  - provider: script
    script: >-
      echo "$DOCKER_ACCESS_TOKEN" | docker login -u shepherdjerred --password-stdin
      && docker push shepherdjerred/overviewer:latest
    on:
      branch: master
  - provider: script
    script: >-
      echo "$GITHUB_ACCESS_TOKEN" | docker login docker.pkg.github.com -u shepherdjerred --password-stdin
      && docker tag shepherdjerred/overviewer:latest docker.pkg.github.com/shepherdjerred-minecraft/overviewer-docker/overviewer:latest
      && docker push docker.pkg.github.com/shepherdjerred-minecraft/overviewer-docker/overviewer:latest
    on:
      branch: master
notifications:
  email: false

